Version: 0.2
phases:
   

  build:
    commands:

      - > 
        sam deploy --template-file sam.yml --stack-name ${samstack} --s3-bucket ${ArtifactS3Bucket}
        --parameter-overrides UniqueIdentifier=${UniqueIdentifier} SecretNames=${SecretNames} ScheduledRate=${ScheduledRate} MailFetchCount=${MailFetchCount}
        --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
